// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKQJ9-r9iz3jmDjpYHBpJuGGheD4B5nw4',
    appId: '1:1038727006738:web:24b21d699ceaaa39b0e6cb',
    messagingSenderId: '1038727006738',
    projectId: 'threadcrafts',
    authDomain: 'threadcrafts.firebaseapp.com',
    storageBucket: 'threadcrafts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqpRS7nLOd96SHlYDqaybOtaZgajMbxdU',
    appId: '1:1038727006738:android:9f11bf680b2449e5b0e6cb',
    messagingSenderId: '1038727006738',
    projectId: 'threadcrafts',
    storageBucket: 'threadcrafts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32euUijsEzHWhZhL40lnJmOXVoeTRKV4',
    appId: '1:1038727006738:ios:ccda17aa4e226ff5b0e6cb',
    messagingSenderId: '1038727006738',
    projectId: 'threadcrafts',
    storageBucket: 'threadcrafts.appspot.com',
    iosBundleId: 'com.example.threadcarfts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32euUijsEzHWhZhL40lnJmOXVoeTRKV4',
    appId: '1:1038727006738:ios:a14c8b3e56417a27b0e6cb',
    messagingSenderId: '1038727006738',
    projectId: 'threadcrafts',
    storageBucket: 'threadcrafts.appspot.com',
    iosBundleId: 'com.example.threadcarfts.RunnerTests',
  );
}
